name: mkdc_3di_manage
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_appauth: ^6.0.6
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  http: ^1.2.1
  number_paginator: ^0.4.1
  shared_preferences: ^2.2.2
  syncfusion_flutter_charts: ^25.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
